# Generated by Django 5.0.2 on 2025-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-fechaPrestamo']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-fecha', '-horaInicio']},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='available_quantity',
            new_name='cantidadDisponible',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='total_quantity',
            new_name='cantidadTotal',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='inventory_number',
            new_name='numeroInventario',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='capacity',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='building',
            new_name='edificio',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='floor',
            new_name='piso',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='type',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='damaged',
            new_name='danado',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='equipment',
            new_name='equipo',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='due_date',
            new_name='fechaDevolucion',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='return_date',
            new_name='fechaEntrega',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loan_date',
            new_name='fechaPrestamo',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='horaFin',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='horaInicio',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reason',
            new_name='motivo',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=16),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto'), ('DANADO', 'Danado')], default='PENDIENTE', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECH', 'Tech'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=16),
        ),
    ]
