# Generated by Django 5.0.2 on 2025-12-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0005_rename_razoncancelacion_reservation_cancel_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Equipo',
        ),
        migrations.RenameModel(
            old_name='Loan',
            new_name='Prestamo',
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['nombre'], 'verbose_name': 'Lab', 'verbose_name_plural': 'Labs'},
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECNICO', 'Tecnico'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=16),
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('motivo', models.CharField(max_length=512)),
                ('razonCancelacion', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=16)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sistema_buap_api.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-horaInicio'],
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
