# Generated by Django 5.0.2 on 2025-12-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0006_rename_equipment_equipo_rename_loan_prestamo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='rol',
        ),
    ]
