# Generated by Django 5.0.2 on 2025-12-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0007_rename_role_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
    ]
